server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    gateway: #网关配置
      routes: # 路由标识
#        - id: # 路由标识 必须唯一
#          uri: # 路由的目标地址
#          predicates: # 路由断言，判断请求是否符合规则
#          filters:
